version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  user-service:
    build: ./user_service
    # ports:
    #   - "5001:5001"
    depends_on:
      - mongo
    restart: always

  course-service:
    build: ./course_service
    # ports:
    #   - "5002:5002"
    depends_on:
      - mongo
    restart: always

  enrollment-service:
    build: ./enrollment_service
    # ports:
    #   - "5003:5003"
    depends_on:
      - mongo
    restart: always

  certificate_service:
    build: ./certificate_service
    # ports:
    #   - "5004:5004"
    depends_on:
      - mongo
    restart: always

  analytics_service:
    build: ./analytics_service
    # ports:
    #   - "5005:5005"
    depends_on:
      - mongo
    restart: always

  feedback_service:
    build: ./feedback_service
    # ports:
    #   - "5006:5006"
    depends_on:
      - mongo
    restart: always

  docs_service:
    build: ./docs_service
    ports:
      - "5007:5007"
    depends_on:
      - mongo
    restart: always

  nginx-gateway:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - course-service
      - enrollment-service
